Controllers/DadosController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using WEBCORE_Clinica_Medica.Data;
using WEBCORE_Clinica_Medica.Models.Dominio;

namespace WEBCORE_Clinica_Medica.Controllers
{
    [Authorize]
    public class DadosController : Controller
    {
        private readonly CultureInfo cultura = CultureInfo.CreateSpecificCulture("pt-BR");

        private readonly Contexto contexto;

        public DadosController(Contexto context)
        {
            contexto = context;
        }

        public IActionResult GerarPacientes()
        {
            Random randNum = new Random();

            string[] nomesMasculinos = { "Miguel", "Arthur", "Bernardo", "Heitor", "Davi", "Lorenzo", "Théo", "Pedro", "Gabriel", "Enzo" };
            string[] nomesFemininos = { "Alice", "Sophia", "Helena", "Valentina", "Laura", "Isabella", "Manuela", "Júlia", "Heloísa", "Luiza" };
            string[] sobrenomes = { "Silva", "Santos", "Oliveira", "Souza", "Rodrigues", "Ferreira", "Alves", "Pereira", "Lima", "Gomes" };
            string[] municipios = { "Assis", "Cândido Mota", "Tarumã", "Presidente Prudente", "Palmital", "Pedrinhas Paulista", "Maracaí", "Cruzália" };
            string[] dominios = { "outlook", "hotmail", "gmail", "uol", "globo", "yahoo" };

            for (int i = 0; i < 20; i++)
            {
                Paciente paciente = new Paciente();

                paciente.nome = (i % 2 == 0) ? nomesMasculinos[i / 2] : nomesFemininos[i / 2];
                paciente.sobrenome = sobrenomes[i / 2];
                paciente.nascimento = DateTime.Parse(randNum.Next(1, 30).ToString().PadLeft(2, '0') + "/" + randNum.Next(1, 12).ToString().PadLeft(2, '0') + "/" + randNum.Next(1960, 2010).ToString(), cultura);
                paciente.sexo = (i % 2 == 0) ? "Masculino" : "Feminino";
                paciente.rg = randNum.Next(1, 99).ToString().PadLeft(2, '0') + "." + randNum.Next(100, 999).ToString() + "." + randNum.Next(100, 999).ToString() + "-" + randNum.Next(1, 9).ToString();
                paciente.cpf = randNum.Next(1, 999).ToString().PadLeft(3, '0') + "." + randNum.Next(100, 999).ToString() + "." + randNum.Next(100, 999).ToString() + "-" + randNum.Next(2, 99).ToString().PadLeft(2, '0');
                paciente.telres = "(18) " + randNum.Next(1, 9999).ToString().PadLeft(4, '0') + "-" + randNum.Next(1, 9999).ToString().PadLeft(4, '0');
                paciente.telcel = "(18) " + randNum.Next(1, 99999).ToString().PadLeft(5, '0') + "-" + randNum.Next(1, 9999).ToString().PadLeft(4, '0');
                paciente.email = paciente.nome.ToLower() + "@" + dominios[randNum.Next() % 6].ToLower() + ".com.br";
                paciente.cep = "19000-000";
                paciente.cidade = municipios[randNum.Next() % 8];
                paciente.estado = "SP";
                paciente.endereco = "Rua " + randNum.Next(1, 20).ToString();
                paciente.numero = (i + 1) * 10;
                paciente.bairro = "Bairro " + randNum.Next(1, 20).ToString();

                contexto.Pacientes.Add(paciente);
            }

            contexto.SaveChanges();

            return View(contexto.Pacientes.OrderBy(o => o.nome).ToList());
        }

        public IActionResult GerarMedicos()
        {
            Random randNum = new Random();

            string[] nomesMasculinos = { "Matheus", "Lucas", "Benjamin", "Nicolas", "Guilherme", "Rafael", "Joaquim", "Samuel", "Henrique", "Gustavo" };
            string[] nomesFemininos = { "Lorena", "Lívia", "Giovanna", "Maria Eduarda", "Beatriz", "Maria Clara", "Cecília", "Lara", "Isadora", "Mariana" };
            string[] sobrenomes = { "Costa", "Ribeiro", "Martins", "Carvalho", "Almeida", "Lopes", "Soares", "Fernandes", "Vieira", "Barbosa" };
            string[] especialidades = { "Cardiologista", "Ortopedista", "Desmatologista", "Oftalmologista", "Neurologista" };
            string[] municipios = { "Assis", "Cândido Mota", "Tarumã", "Presidente Prudente", "Palmital", "Pedrinhas Paulista", "Maracaí", "Cruzália" };
            string[] dominios = { "outlook", "hotmail", "gmail", "uol", "globo", "yahoo" };

            for (int i = 0; i < 20; i++)
            {
                Medico medico = new Medico();

                medico.nome = (i % 2 == 0) ? nomesMasculinos[i / 2] : nomesFemininos[i / 2];
                medico.sobrenome = sobrenomes[i / 2];
                medico.nascimento = DateTime.Parse(randNum.Next(1, 30).ToString() + "/" + randNum.Next(1, 12).ToString() + "/" + randNum.Next(1960, 2003).ToString(), cultura);
                medico.sexo = (i % 2 == 0) ? "Masculino" : "Feminino";
                medico.crm = "00000000";
                medico.especialidade = especialidades[randNum.Next() % 5]; ;
                medico.rg = randNum.Next(1, 99).ToString().PadLeft(2, '0') + "." + randNum.Next(100, 999).ToString() + "." + randNum.Next(100, 999).ToString() + "-" + randNum.Next(1, 9).ToString();
                medico.cpf = randNum.Next(1, 999).ToString().PadLeft(3, '0') + "." + randNum.Next(100, 999).ToString() + "." + randNum.Next(100, 999).ToString() + "-" + randNum.Next(1, 99).ToString().PadLeft(2, '0');
                medico.telres = "(18) " + randNum.Next(1, 9999).ToString().PadLeft(4, '0') + "-" + randNum.Next(1, 9999).ToString().PadLeft(4, '0');
                medico.telcel = "(18) " + randNum.Next(1, 99999).ToString().PadLeft(5, '0') + "-" + randNum.Next(1, 9999).ToString().PadLeft(4, '0');
                medico.email = medico.nome.ToLower() + "@" + dominios[randNum.Next() % 6].ToLower() + ".com.br";
                medico.cep = "19000-000";
                medico.cidade = municipios[randNum.Next() % 8];
                medico.estado = "SP";
                medico.endereco = "Rua " + randNum.Next(1, 20).ToString();
                medico.numero = (i + 1) * 10;
                medico.bairro = "Bairro " + randNum.Next(1, 20).ToString();

                contexto.Medicos.Add(medico);
            }

            contexto.SaveChanges();

            return View(contexto.Medicos.OrderBy(o => o.nome).ToList());
        }

        public IActionResult GerarFuncionarios()
        {
            Random randNum = new Random();

            string[] nomesMasculinos = { "Murilo", "Pedro Henrique", "Pietro", "Felipe", "Isaac", "Daniel", "Anthony", "Leonardo", "Eduardo", "Victor" };
            string[] nomesFemininos = { "Ana Júlia", "Ana Clara", "Elisa", "Melissa", "Yasmin", "Maria Alice", "Isabelly", "Lvínia", "Esther", "Sarah" };
            string[] sobrenomes = { "Rocha", "Dias", "Nascimento", "Andrade", "Moreira", "Nunes", "Marques", "Machado", "Freitas", "Cardoso" };
            string[] cargos = { "Secretário", "Assistente Administrativo", "Analista de Sistema" };
            string[] municipios = { "Assis", "Cândido Mota", "Tarumã", "Presidente Prudente", "Palmital", "Pedrinhas Paulista", "Maracaí", "Cruzália" };
            string[] dominios = { "outlook", "hotmail", "gmail", "uol", "globo", "yahoo" };

            for (int i = 0; i < 20; i++)
            {
                Funcionario funcionario = new Funcionario();

                funcionario.nome = (i % 2 == 0) ? nomesMasculinos[i / 2] : nomesFemininos[i / 2];
                funcionario.sobrenome = sobrenomes[i / 2];
                funcionario.nascimento = DateTime.Parse(randNum.Next(1, 30).ToString() + "/" + randNum.Next(1, 12).ToString() + "/" + randNum.Next(1960, 2003).ToString(), cultura);
                funcionario.sexo = (i % 2 == 0) ? "Masculino" : "Feminino";
                funcionario.cargo = cargos[randNum.Next() % 3];
                funcionario.rg = randNum.Next(1, 99).ToString().PadLeft(2, '0') + "." + randNum.Next(100, 999).ToString() + "." + randNum.Next(100, 999).ToString() + "-" + randNum.Next(1, 9).ToString();
                funcionario.cpf = randNum.Next(1, 999).ToString().PadLeft(3, '0') + "." + randNum.Next(100, 999).ToString() + "." + randNum.Next(100, 999).ToString() + "-" + randNum.Next(1, 99).ToString().PadLeft(2, '0');
                funcionario.telres = "(18) " + randNum.Next(1, 9999).ToString().PadLeft(4, '0') + "-" + randNum.Next(1, 9999).ToString().PadLeft(4, '0');
                funcionario.telcel = "(18) " + randNum.Next(1, 99999).ToString().PadLeft(5, '0') + "-" + randNum.Next(1, 9999).ToString().PadLeft(4, '0');
                funcionario.email = funcionario.nome.ToLower() + "@" + dominios[randNum.Next() % 6].ToLower() + ".com.br";
                funcionario.cep = "19000-000";
                funcionario.cidade = municipios[randNum.Next() % 8];
                funcionario.estado = "SP";
                funcionario.endereco = "Rua " + randNum.Next(1, 20).ToString();
                funcionario.numero = (i + 1) * 10;
                funcionario.bairro = "Bairro " + randNum.Next(1, 20).ToString();

                contexto.Funcionarios.Add(funcionario);
            }

            contexto.SaveChanges();

            return View(contexto.Funcionarios.OrderBy(o => o.nome).ToList());
        }

        public IActionResult GerarProdutos()
        {
            Random randNum = new Random();

            string[] produtos = { "Produto 1", "Produto 2", "Produto 3", "Produto 4", "Produto 5", "Produto 6", "Produto 7", "Produto 8", "Produto 9", "Produto 10" };

            for (int i = 0; i < 10; i++)
            {
                Produto produto = new Produto();

                produto.descricao = produtos[i];
                produto.preco = Math.Round(randNum.NextDouble() * 100, 2);
                produto.estoque = randNum.Next() % 15;
                produto.total = produto.preco * produto.estoque;

                contexto.Produtos.Add(produto);
            }

            contexto.SaveChanges();

            return View(contexto.Produtos.OrderBy(o => o.id).ToList());
        }

Controllers/MedicosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WEBCORE_Clinica_Medica.Data;
using WEBCORE_Clinica_Medica.Models.Dominio;

namespace WEBCORE_Clinica_Medica.Controllers
{
    [Authorize]
    public class MedicosController : Controller
    {
        private readonly Contexto _context;

        public MedicosController(Contexto context)
        {
            _context = context;
        }

        // GET: Medicos
        public async Task<IActionResult> Index(string nomeSobrenome)
        {
            if (!String.IsNullOrEmpty(nomeSobrenome))
            {
                ViewData["FilterByName"] = nomeSobrenome;

                var medicos = from medico in _context.Medicos
                              select medico;

                medicos = medicos.Where(m => m.nome.Contains(nomeSobrenome) || m.sobrenome.Contains(nomeSobrenome));

                return View(await medicos.AsNoTracking().ToListAsync());
            }
            return View(await _context.Medicos.ToListAsync());
        }

        // GET: Medicos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var medico = await _context.Medicos
                .FirstOrDefaultAsync(m => m.id == id);
            if (medico == null)
            {
                return NotFound();
            }

            return View(medico);
        }

        // GET: Medicos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Medicos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,nome,sobrenome,nascimento,sexo,crm,especialidade,rg,cpf,telres,telcel,email,cep,cidade,estado,endereco,numero,bairro,complemento")] Medico medico)
        {
            if (ModelState.IsValid)
            {
                _context.Add(medico);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(medico);
        }

        // GET: Medicos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var medico = await _context.Medicos.FindAsync(id);
            if (medico == null)
            {
                return NotFound();
            }
            return View(medico);
        }

        // POST: Medicos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,nome,sobrenome,nascimento,sexo,crm,especialidade,rg,cpf,telres,telcel,email,cep,cidade,estado,endereco,numero,bairro,complemento")] Medico medico)
        {
            if (id != medico.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(medico);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MedicoExists(medico.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(medico);
        }

        // GET: Medicos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var medico = await _context.Medicos
                .FirstOrDefaultAsync(m => m.id == id);
            if (medico == null)
            {
                return NotFound();
            }

            return View(medico);
        }

        // POST: Medicos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var medico = await _context.Medicos.FindAsync(id);
            _context.Medicos.Remove(medico);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MedicoExists(int id)
        {
            return _context.Medicos.Any(e => e.id == id);
        }

        public ActionResult VerificarCPF(string cpf, int id)
        {
            bool cpfExiste = _context.Medicos.Where(p => p.cpf == cpf && p.id != id).Count() == 0;
            return Json(cpfExiste);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WEBCORE_Clinica_Medica</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/menu.css" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/imagens/icon-principal.png" width="45"></a>
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TECHMEDICINE</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Cadastros
                            </a>
                            <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                                <li><a class="nav-link text-dark" asp-area="" asp-controller="Pacientes" asp-action="Index">Pacientes</a></li>
                                <li><a class="nav-link text-dark" asp-area="" asp-controller="Medicos" asp-action="Index">Médicos</a></li>
                                <li><a class="nav-link text-dark" asp-area="" asp-controller="Funcionarios" asp-action="Index">Funcionários</a></li>
                                <li><a class="nav-link text-dark" asp-area="" asp-controller="Agendamentos" asp-action="Index">Agendamentos</a></li>
                                <!-- <li><a class="nav-link text-dark" href="#">Atendimentos</a></li> -->
                                <li><a class="nav-link text-dark" asp-area="" asp-controller="Produtos" asp-action="Index">Produtos</a></li>
                                <li><a class="nav-link text-dark" asp-area="" asp-controller="Movimentacoes" asp-action="Index">Movimentações</a></li>
                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Consultas
                            </a>
                            <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                                <h6 class="dropdown-header">Consultas de várias origens </h6>
                                <li><a class="nav-link text-dark" asp-area="" asp-controller="Consulta" asp-action="ListarPacienteAgendamento">Detalhes Agendamentos</a></li>
                                <h6 class="dropdown-header">Consultas de agrupamento </h6>
                                <li><a class="nav-link text-dark" asp-area="" asp-controller="Consulta" asp-action="TotalMovimentacoes">Total de Movimentações</a></li>
                                <h6 class="dropdown-header">Consultas de pivot de dados</h6>
                                <li><a class="nav-link text-dark" asp-area="" asp-controller="Consulta" asp-action="PivotMovimentacoes">Pivot Movimentações</a></li>
                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Gerar Dados
                            </a>
                            <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                                <li><a class="nav-link text-primary" asp-area="" asp-controller="Dados" asp-action="GerarPacientes">Gerar Pacientes</a></li>
                                <li><a class="nav-link text-primary" asp-area="" asp-controller="Dados" asp-action="GerarMedicos">Gerar Médicos</a></li>
                                <li><a class="nav-link text-primary" asp-area="" asp-controller="Dados" asp-action="GerarFuncionarios">Gerar Funcionários</a></li>
                                <li><a class="nav-link text-primary" asp-area="" asp-controller="Dados" asp-action="GerarProdutos">Gerar Produtos</a></li>
                                <li><a class="nav-link text-primary" asp-area="" asp-controller="Dados" asp-action="GerarAgendamentos">Gerar Agendamentos</a></li>
                                <div class="dropdown-divider"></div>
                                <li><a class="nav-link text-danger" asp-area="" asp-controller="Dados" asp-action="LimparTabelas">Limpar Tabelas</a></li>
                            </ul>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - WEBCORE_Clinica_Medica - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacidade</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>